spring.application.name=products
# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/Inventario
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================================================
# SWAGGER CONFIGURATION
# =============================================================================
springdoc.api-docs.version=openapi_3_0
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha


# clave que usan ambos micros
products.api.key=${API_KEY_SECRET}