spring.application.name=products
# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
spring.datasource.url=jdbc:postgresql://${HOSTNAME}:${PORT}/Inventario
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================================================
# SWAGGER CONFIGURATION
# =============================================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha